import "~/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { AuthProvider } from "./auth/AuthProvider";
import { poppins } from "~/utils/font";
import { Toaster } from "react-hot-toast";
import { ImageProvider } from "~/context/ImageFormContext";
import Modal from "~/utils/Modal";
import { HeaderProvider } from "~/context/HeaderContext";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <AuthProvider>
      <HeaderProvider>
        <ImageProvider>
          <html lang="en" className={`${poppins.className}`}>
            <body>
              <TRPCReactProvider>
                <header className="bg-black">
                  <Header />
                </header>
                <Modal />
                <Toaster position="top-right" />
                {children}
                <footer className="bg-gradient-to-b from-pink-600 to-yellow-600">
                  <Footer />
                </footer>
              </TRPCReactProvider>
            </body>
          </html>
        </ImageProvider>
      </HeaderProvider>
    </AuthProvider>
  );
}
